services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
    ports:
      - 5173:5173

# La sección comentada a continuación es un ejemplo de cómo definir una base de datos PostgreSQL
# que tu aplicación puede usar. `depends_on` le dice a Docker Compose que
# inicie la base de datos antes que tu aplicación. El volumen `db-data` persiste
# los datos de la base de datos entre reinicios del contenedor. El secreto `db-password` se utiliza
# para establecer la contraseña de la base de datos. Debes crear `db/password.txt` y agregar
# una contraseña de tu elección antes de ejecutar `docker compose up`.
#     depends_on:
#       db:
#         condition: service_healthy
#   db:
#     image: postgres
#     restart: always
#     user: postgres
#     secrets:
#       - db-password
#     volumes:
#       - db-data:/var/lib/postgresql/data
#     environment:
#       - POSTGRES_DB=example
#       - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
#     expose:
#       - 5432
#     healthcheck:
#       test: [ "CMD", "pg_isready" ]
#       interval: 10s
#       timeout: 5s
#       retries: 5
# volumes:
#   db-data:
# secrets:
#   db-password:
#     file: db/password.txt
